version: "3"
services:
  mongo:
     container_name: mongodb
     image : mongo
     ports:
      - "127.0.0.1:27017:27017"
   
     volumes: 
      - ./mongo-volume:/data/db
    
    
              
  app: 
     image: sajaweb/realestate_app
     container_name: realestateapp
     environment:
       - APIKEY=${SMS_KEY}  
     build:  
        context: .
        dockerfile: Dockerfile    
     ports: 
      - "8080:8000"
     depends_on:
      - mongo
 
