version:"3"
service :
  mongo:
    image:mongo
    ports:
     - "27017:27017"
     envitonment:
      - MONGO_INITDB_DATABASE=amlak
     volumes:
      - ./mongo-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    app:
     build:.
     ports:
      _ "8080:8080"
     depends_on:
     - mongo   
