name: deploy-user

on:
  workflow_dispatch:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t sajaweb/realestate_app -f Dockerfile .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sajaweb/realestate_app
      - run: docker logout
      - uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          SMS_KEY:         ${{secrets.SMS_KEY}}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: DOCKER_USERNAME,DOCKER_PASSWORD,SMS_KEY
          script: |
            cd backend
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull sajaweb/realestate_app
            docker-compose -e API_KEY=$SMS_KEY  up  -d 
            docker logout
            