name: deploy-user

on:
  workflow_dispatch:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -e
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sajaweb/realestate_app
      - run: docker logout
      - uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PRIVATE_KEY_PASSPHRASE }}
          envs: DOCKER_USERNAME,DOCKER_PASSWORD
          script: |
            cd backend
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull sajaweb/realestate_app
            docker-compose  up  -d 
            docker logout
            